sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

install: npm install

script:
  - ng build --prod --aot
  - ng test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN
  app: angular-devops